board: toradex: Fix fastboot build
NXP common code now calls a board function mmc_map_to_kernel_blk().
Provide a weak function in common code for boards not requiring
special handling.

Introduced by:
commit 75f2d65ebf90 ("MLK-18591-3 android: Add FSL android fastboot support")
commit 3000cd67e063 ("MA-20238 Pass boot device from bootloader")

Prevents:
aarch64-none-linux-gnu-ld.bfd: boot/image-android.c:428: undefined reference to `mmc_map_to_kernel_blk'

Taken from boards/freescale/common/mmc.c

NXP downstream specific

Upstream-Status: Inappropriate [other]
Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>