configs: verdin-am62_a53_defconfig: add CONFIG_BOOTCOMMAND
Since commit 2f88872eb39c ("Kconfig: Add default bootcmd for all devices
of ARCH_K3"), a default bootcommand is set based on ARCH_K3 config. As
we not have these variables set, this causes the following error:

Verdin AM62 # boot
Error: "envboot" not defined
Error: "bootcmd_ti_mmc" not defined

Therefore, overwrite the BOOTCOMMAND to run the distro_bootcmd instead.

The commit 2f88872eb39c is not present upstream, therefore this issue is
downstream only.

Upstream-Status: Inappropriate [other]
Fixes: 2f88872eb39c ("Kconfig: Add default bootcmd for all devices of ARCH_K3")
Signed-off-by: Hiago De Franco <hiago.franco@toradex.com>